import json
from pathlib import Path
from types import SimpleNamespace

import openai
import pytest

from pipeline.ai import get_ai_provider
from pipeline.errors import PipelineError
from pipeline.planner import create_plan
from pipeline.spec_parser import parse_feature_spec


def test_openai_responses_provider_uses_structured_outputs(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[dict[str, object]] = []
    constructed: list[dict[str, object]] = []

    class FakeUsage:
        def model_dump(self, mode: str) -> dict[str, int]:
            return {"input_tokens": 10, "output_tokens": 20}

    class FakeResponses:
        def create(self, **kwargs: object) -> SimpleNamespace:
            calls.append(kwargs)
            return SimpleNamespace(
                id="resp_test",
                status="completed",
                output_text=json.dumps(
                    {
                        "summary": ["Generated by mocked OpenAI."],
                        "files": [
                            {
                                "path": "demo_app/src/demo_app/discount_calculator.py",
                                "purpose": "Generated implementation.",
                                "content": "def calculate_discounted_price():\n    return 1\n",
                                "acceptance_criteria": ["AC-001"],
                            }
                        ],
                    }
                ),
                usage=FakeUsage(),
            )

    class FakeOpenAI:
        def __init__(self, **kwargs: object) -> None:
            constructed.append(kwargs)
            self.responses = FakeResponses()

    monkeypatch.setattr(openai, "OpenAI", FakeOpenAI)
    monkeypatch.setenv("PIPELINE_AI_PROVIDER", "openai")
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test-secret")
    monkeypatch.setenv("OPENAI_MODEL", "gpt-test")
    monkeypatch.setenv("OPENAI_REASONING_EFFORT", "medium")

    spec = parse_feature_spec(Path("specs/examples/discount_calculator.yaml"))
    plan = create_plan(spec, "run-1", "spec-hash")

    provider = get_ai_provider()
    change_set = provider.generate_changes(spec, plan)

    assert constructed == [{"api_key": "sk-test-secret", "base_url": "https://api.openai.com/v1"}]
    assert calls
    request = calls[0]
    assert request["model"] == "gpt-test"
    assert request["reasoning"] == {"effort": "medium"}
    assert request["store"] is False
    assert request["text"]["format"]["type"] == "json_schema"  # type: ignore[index]
    assert change_set.provider == "openai-responses"
    assert change_set.model == "gpt-test"
    assert provider.last_interaction_metadata["response"]["id"] == "resp_test"
    assert "sk-test-secret" not in json.dumps(provider.last_interaction_metadata)


def test_openai_provider_requires_key(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PIPELINE_AI_PROVIDER", "openai")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    with pytest.raises(PipelineError, match="OPENAI_API_KEY is required"):
        get_ai_provider()
